myservice:
    extends:
        file: "docker-compose-prd.yml"
        service: myservice
    environment: 
        SPRING_PROFILE: dev
  # It calls a grunt task to start the node server with a file watch so if any files change 
  # (propagated to the container by volume mounting) the server is restarted.
    command: ./node_modules/.bin/grunt serve
    volumes:
        - myservice:/src/myservice

    